language: java
env:
  global:
    - KEYCLOAK_VERSION=5.0.0
    - PROMETHEUS_VERSION=0.3.0
install: "./gradlew assemble"
script:
    - "./gradlew test"
    - "./gradlew -Pversion=${TRAVIS_TAG} -PkeycloakVersion=${KEYCLOAK_VERSION} -PprometheusVersion=${PROMETHEUS_VERSION} jar"
deploy:
  provider: releases
  api_key:
    secure: $API_KEY
  file: "build/libs/keycloak-metrics-spi-${TRAVIS_TAG}.jar"
  skip_cleanup: true
  on:
    repo: coliquio/keycloak-metrics-spi
    tags: true
